Port fix from upstream where the related table information was not being indexed
* When indexing related table information the affected code should be referencing the related table rather than the current table.
* This was causing:

 ``` bash
 [2015-02-27 10:28:10,918][DEBUG][action.index             ] [Meteorite] [collectiveaccess][0], node[LmM8-kmMRXmA0M4YdC5Vew], [P], s[STARTED]: Failed to execute [index {[collectiveaccess][ca_loans][2], source[{"ca_loans.idno":["7087"],"ca_loans.type_id":["loan out out 120"],"ca_loans.hier_loan_id":["2","P26608018"],"ca_loans.access":["0"],"ca_loans.status":["0"],"ca_loans.deleted":["0"],"ca_loans.loan_status":["5299 ;  In loan to other organisation","5299 ;  In loan to other organisation Root node for loan_status_types In loan to other organisation"],"ca_loan_labels.name":["7087"],"ca_loans.hier_loan_id\/8":["P26608018"],"ca_object_labels.name":["P26608018 Trachichthyidae <em>Optivus agrammus<\/em>  Hutchins, J.B., et al."],"ca_object_labels.name\/8":["P26608018 Trachichthyidae <em>Optivus agrammus<\/em>  Hutchins, J.B., et al."],"loan_id":"2","ca_loans.loan_id":"38966","created":"2015-02-26T16:47:14+08:00","created_user_id":null,"modified":"2015-02-26T16:47:14+08:00","modified_user_id":null}]}]
 org.elasticsearch.index.mapper.MapperParsingException: failed to parse [ca_loans.hier_loan_id]
 	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
 	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:613)
 	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:601)
 	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:458)
 	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:516)
 	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:460)
 	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:374)
 	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:205)
 	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:556)
 	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:426)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.NumberFormatException: For input string: "P26608018"
 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
 	at java.lang.Double.parseDouble(Double.java:540)
 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.doubleValue(AbstractXContentParser.java:111)
 	at org.elasticsearch.index.mapper.core.DoubleFieldMapper.innerParseCreateField(DoubleFieldMapper.java:297)
 	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:194)
 	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:405)
 	... 12 more

```